[automx]
provider = roessner-net.de
domains = roessner-net.de alltagswahnsinn.de alsfeld.email ra-roessner-merle.de roessner-net.com roessner.email
autodiscover_v2 = no

[DEFAULT]
account_name = Rößner-Network-Solutions
account_name_short = R.N.S.

[global]
backend = static

imap = yes
imap_server = mail.roessner-net.de
imap_port = 993
imap_encryption = ssl
imap_auth = oauth2, plaintext

smtp = yes
smtp_server = mail.roessner-net.de
smtp_port = 465
smtp_encryption = ssl
smtp_auth = oauth2, plaintext
smtp_default = yes

oauth_issuer = https://login.authserv.me
oauth_auth_url = https://login.authserv.me/oidc/authorize
oauth_token_url = https://login.authserv.me/oidc/token
oauth_scope = openid offline_access mail:account:read
