from __future__ import annotations

import json
from pathlib import Path

import pytest

from automx.cli import build_parser, main
from automx.commands.openapi import schema, serialized_schema
from automx.commands.probe import ProbeClient

ROOT = Path(__file__).parents[1]
CONFIG = ROOT / "contrib/e2e/automx.conf"


def test_top_level_help_is_english_and_lists_modular_commands() -> None:
    help_text = build_parser().format_help()

    assert "Operate, validate, publish, and probe" in help_text
    for command in ("serve", "config", "openapi", "dns", "pacc", "probe"):
        assert command in help_text
    assert "pacc-digest" not in help_text
    assert "validate-config" not in help_text


def test_config_validation_and_expected_error_exit_codes(
    capsys: pytest.CaptureFixture[str],
) -> None:
    assert main(["config", "validate", "--config", str(CONFIG)]) == 0
    assert capsys.readouterr().out == "Configuration valid for example.test.\n"

    assert main(["config", "validate", "--config", "/does/not/exist"]) == 2
    captured = capsys.readouterr()
    assert captured.out == ""
    assert "automx:" in captured.err


def test_pacc_digest_and_dns_zone_output_are_exact(
    capsys: pytest.CaptureFixture[str],
) -> None:
    arguments = ["--config", str(CONFIG), "--domain", "example.test"]
    assert main(["pacc", "digest", *arguments]) == 0
    digest = "v=UAAC1; a=sha256; d=PZ0Wgfaw7fs6Jo/1YHAtnt7tVoMpQO85rN/jI5dK59I="
    assert capsys.readouterr().out == f"{digest}\n"

    assert (
        main(
            [
                "dns",
                "records",
                *arguments,
                "--service-host",
                "config.example.net.",
                "--ttl",
                "300",
            ]
        )
        == 0
    )
    assert capsys.readouterr().out == (
        "; Generated by automx (read-only; review before applying)\n"
        "autoconfig.example.test. 300 IN CNAME config.example.net.\n"
        "autodiscover.example.test. 300 IN CNAME config.example.net.\n"
        "_autodiscover._tcp.example.test. 300 IN SRV "
        "0 0 443 config.example.net.\n"
        "ua-auto-config.example.test. 300 IN CNAME config.example.net.\n"
        f'_ua-auto-config.example.test. 300 IN TXT "{digest}"\n'
    )


def test_dns_json_is_machine_readable_and_explicitly_read_only(
    capsys: pytest.CaptureFixture[str],
) -> None:
    assert (
        main(
            [
                "dns",
                "records",
                "--config",
                str(CONFIG),
                "--service-host",
                "automx.example.net",
                "--format",
                "json",
            ]
        )
        == 0
    )
    document = json.loads(capsys.readouterr().out)
    assert document["mode"] == "read-only"
    assert len(document["records"]) == 5
    assert {record["type"] for record in document["records"]} == {"CNAME", "SRV", "TXT"}


def test_openapi_is_valid_deterministic_and_marks_experimental_routes(
    tmp_path: Path,
) -> None:
    document = schema(str(CONFIG))
    first = serialized_schema(str(CONFIG))
    second = serialized_schema(str(CONFIG))

    assert document["openapi"].startswith("3.1.")
    assert first == second
    assert "/health/ready" not in document["paths"]
    path_operation = document["paths"][
        "/autodiscover/autodiscover.json/v1.0/{email_address}"
    ]["get"]
    assert path_operation["x-automx-status"] == "experimental"
    operation_ids = [
        operation["operationId"]
        for path in document["paths"].values()
        for method, operation in path.items()
        if method in {"get", "post", "put", "patch", "delete"}
    ]
    assert len(operation_ids) == len(set(operation_ids))

    output = tmp_path / "openapi.json"
    assert main(["openapi", "export", "--config", str(CONFIG), "--output", str(output)]) == 0
    assert output.read_text(encoding="utf-8") == first
    assert main(["openapi", "check", "--config", str(CONFIG)]) == 0


def test_probe_requires_explicit_opt_in_for_plain_http_and_never_takes_a_password(
    capsys: pytest.CaptureFixture[str],
) -> None:
    with pytest.raises(ValueError, match="allow-insecure-http"):
        ProbeClient(
            "http://127.0.0.1:8000",
            timeout=1,
            allow_insecure_http=False,
            basic_auth_environment=None,
        )

    with pytest.raises(SystemExit) as exited:
        build_parser().parse_args(["probe", "all", "--help"])
    assert exited.value.code == 0
    help_text = capsys.readouterr().out
    assert "--basic-auth-env" in help_text
    assert "--password" not in help_text
