from __future__ import annotations

import argparse
import json
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from automx.app import create_app
from automx.cli import build_parser, main
from automx.commands import serve
from automx.commands.openapi import schema, serialized_schema
from automx.commands.probe import ProbeClient
from automx.configuration import ConfigurationRepository
from automx.documents import (
    autoconfig_document,
    autodiscover_document,
    mobileconfig_document,
    pacc_document,
)
from automx.renderers.autodiscover import AutodiscoverSchema
from automx.renderers.pacc import pacc_digest_record

ROOT = Path(__file__).parents[1]
CONFIG = ROOT / "contrib/e2e/automx.conf"


def test_serve_uses_only_the_route_template_access_log(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    captured: dict[str, object] = {}

    def fake_run(_app: object, **kwargs: object) -> None:
        captured.update(kwargs)

    monkeypatch.setattr(serve.uvicorn, "run", fake_run)

    assert serve.run(
        argparse.Namespace(config=str(CONFIG), host="127.0.0.1", port=8000)
    ) == 0
    assert captured["access_log"] is False
    log_config = captured["log_config"]
    assert isinstance(log_config, dict)
    assert log_config["loggers"]["automx.access"] == {
        "handlers": ["default"],
        "level": "INFO",
        "propagate": False,
    }


def test_top_level_help_is_english_and_lists_modular_commands() -> None:
    help_text = build_parser().format_help()

    assert "Operate, validate, publish, and probe" in help_text
    for command in ("serve", "config", "openapi", "dns", "pacc", "probe", "render"):
        assert command in help_text
    assert "pacc-digest" not in help_text
    assert "validate-config" not in help_text


def test_config_validation_and_expected_error_exit_codes(
    capsys: pytest.CaptureFixture[str],
) -> None:
    assert main(["config", "validate", "--config", str(CONFIG)]) == 0
    assert capsys.readouterr().out == "Configuration valid for example.test.\n"

    assert main(["config", "validate", "--config", "/does/not/exist"]) == 2
    captured = capsys.readouterr()
    assert captured.out == ""
    assert "automx:" in captured.err


def test_pacc_digest_and_dns_zone_output_are_exact(
    capsys: pytest.CaptureFixture[str],
) -> None:
    arguments = ["--config", str(CONFIG), "--domain", "example.test"]
    assert main(["pacc", "digest", *arguments]) == 0
    digest = "v=UAAC1; a=sha256; d=x4UCWvDe1w8ERAAFF8yaWut70DP8PNqw+p0oRsr6zxE="
    assert capsys.readouterr().out == f"{digest}\n"

    assert (
        main(
            [
                "dns",
                "records",
                *arguments,
                "--service-host",
                "config.example.net.",
                "--ttl",
                "300",
            ]
        )
        == 0
    )
    assert capsys.readouterr().out == (
        "; Generated by automx (read-only; review before applying)\n"
        "autoconfig.example.test. 300 IN CNAME config.example.net.\n"
        "autodiscover.example.test. 300 IN CNAME config.example.net.\n"
        "_autodiscover._tcp.example.test. 300 IN SRV "
        "0 0 443 config.example.net.\n"
        "ua-auto-config.example.test. 300 IN CNAME config.example.net.\n"
        f'_ua-auto-config.example.test. 300 IN TXT "{digest}"\n'
    )


def test_dns_json_is_machine_readable_and_explicitly_read_only(
    capsys: pytest.CaptureFixture[str],
) -> None:
    assert (
        main(
            [
                "dns",
                "records",
                "--config",
                str(CONFIG),
                "--service-host",
                "automx.example.net",
                "--format",
                "json",
            ]
        )
        == 0
    )
    document = json.loads(capsys.readouterr().out)
    assert document["mode"] == "read-only"
    assert len(document["records"]) == 5
    assert {record["type"] for record in document["records"]} == {"CNAME", "SRV", "TXT"}


def test_dns_records_omit_a_self_referential_canonical_cname(
    capsys: pytest.CaptureFixture[str],
) -> None:
    assert (
        main(
            [
                "dns",
                "records",
                "--config",
                str(CONFIG),
                "--domain",
                "example.test",
                "--service-host",
                "autoconfig.example.test",
                "--format",
                "json",
            ]
        )
        == 0
    )
    document = json.loads(capsys.readouterr().out)
    records = document["records"]
    assert len(records) == 4
    assert not any(
        record["name"] == "autoconfig.example.test"
        and record["type"] == "CNAME"
        for record in records
    )


def test_openapi_is_valid_deterministic_and_marks_experimental_routes(
    tmp_path: Path,
) -> None:
    document = schema(str(CONFIG))
    first = serialized_schema(str(CONFIG))
    second = serialized_schema(str(CONFIG))

    assert document["openapi"].startswith("3.1.")
    assert first == second
    assert "/health/ready" not in document["paths"]
    path_operation = document["paths"][
        "/autodiscover/autodiscover.json/v1.0/{email_address}"
    ]["get"]
    assert path_operation["x-automx-status"] == "experimental"
    assert set(
        document["paths"]["/mail/config-v1.1.xml"]["get"]["responses"]["200"][
            "content"
        ]
    ) == {"text/xml"}
    assert set(
        document["paths"]["/autodiscover/autodiscover.xml"]["post"]["responses"][
            "200"
        ]["content"]
    ) == {"text/xml"}
    assert set(
        document["paths"]["/mobileconfig"]["post"]["responses"]["200"]["content"]
    ) == {"application/x-apple-aspen-config"}
    validation_paths = (
        "/mail/config-v1.1.xml",
        "/.well-known/autoconfig/mail/config-v1.1.xml",
        "/autodiscover/autodiscover.json/v1.0/{email_address}",
        "/autodiscover/autodiscover.json",
    )
    for path in validation_paths:
        operation = document["paths"][path]["get"]
        assert "422" not in operation["responses"]
        assert set(operation["responses"]["4XX"]["content"]) == {"application/json"}
    mobileconfig_responses = document["paths"]["/mobileconfig"]["post"]["responses"]
    assert set(mobileconfig_responses["400"]["content"]) == {"application/json"}
    assert set(mobileconfig_responses["422"]["content"]) == {"application/json"}
    operation_ids = [
        operation["operationId"]
        for path in document["paths"].values()
        for method, operation in path.items()
        if method in {"get", "post", "put", "patch", "delete"}
    ]
    assert len(operation_ids) == len(set(operation_ids))

    output = tmp_path / "openapi.json"
    assert main(["openapi", "export", "--config", str(CONFIG), "--output", str(output)]) == 0
    assert output.read_text(encoding="utf-8") == first
    assert main(["openapi", "check", "--config", str(CONFIG)]) == 0


def test_probe_requires_explicit_opt_in_for_plain_http_and_never_takes_a_password(
    capsys: pytest.CaptureFixture[str],
) -> None:
    with pytest.raises(ValueError, match="allow-insecure-http"):
        ProbeClient(
            "http://127.0.0.1:8000",
            timeout=1,
            allow_insecure_http=False,
            basic_auth_environment=None,
        )

    with pytest.raises(SystemExit) as exited:
        build_parser().parse_args(["probe", "all", "--help"])
    assert exited.value.code == 0
    help_text = capsys.readouterr().out
    assert "--basic-auth-env" in help_text
    assert "--password" not in help_text


def test_render_commands_write_exact_shared_document_bytes(
    capsysbinary: pytest.CaptureFixture[bytes],
) -> None:
    repository = ConfigurationRepository.from_path(CONFIG)
    email = "probe@example.test"
    common = ["--config", str(CONFIG)]

    cases = (
        (
            ["render", "autoconfig", *common, "--email", email],
            autoconfig_document(repository, email),
        ),
        (
            [
                "render",
                "autodiscover",
                *common,
                "--email",
                email,
                "--schema",
                "outlook",
            ],
            autodiscover_document(repository, email, AutodiscoverSchema.OUTLOOK),
        ),
        (
            [
                "render",
                "autodiscover",
                *common,
                "--email",
                email,
                "--schema",
                "mobilesync",
            ],
            autodiscover_document(repository, email, AutodiscoverSchema.MOBILE),
        ),
        (
            ["render", "pacc", *common, "--domain", "example.test"],
            pacc_document(repository, "example.test"),
        ),
        (
            ["render", "mobileconfig", *common, "--email", email],
            mobileconfig_document(repository, email),
        ),
    )
    for arguments, expected in cases:
        assert main(arguments) == 0
        captured = capsysbinary.readouterr()
        assert captured.out == expected
        assert captured.err == b""


def test_render_pacc_preserves_digest_parity(
    capsysbinary: pytest.CaptureFixture[bytes],
) -> None:
    arguments = ["--config", str(CONFIG), "--domain", "example.test"]

    assert main(["render", "pacc", *arguments]) == 0
    body = capsysbinary.readouterr().out
    assert main(["pacc", "digest", *arguments]) == 0
    digest = capsysbinary.readouterr().out.decode("ascii").strip()

    assert digest == pacc_digest_record(body)


def test_render_autoconfig_preserves_static_document_and_asgi_parity(
    tmp_path: Path,
    capsysbinary: pytest.CaptureFixture[bytes],
) -> None:
    expected = (
        b'<?xml version="1.0"?><clientConfig version="1.2">'
        b'<emailProvider id="example.test"/></clientConfig>'
    )
    (tmp_path / "autoconfig.xml").write_bytes(expected)
    config = tmp_path / "automx.conf"
    config.write_text(
        """
[automx]
provider = example.test
domains = example.test
[global]
backend = file
autoconfig = autoconfig.xml
""",
        encoding="utf-8",
    )

    assert (
        main(
            [
                "render",
                "autoconfig",
                "--config",
                str(config),
                "--email",
                "probe@example.test",
            ]
        )
        == 0
    )
    cli_body = capsysbinary.readouterr().out
    response = TestClient(create_app(config_path=config)).get(
        "/mail/config-v1.1.xml",
        params={"emailaddress": "probe@example.test"},
    )

    assert cli_body == expected
    assert response.content == cli_body


def test_render_mobileconfig_preserves_common_name_and_asgi_parity(
    capsysbinary: pytest.CaptureFixture[bytes],
) -> None:
    arguments = [
        "--config",
        str(CONFIG),
        "--email",
        "probe@example.test",
        "--common-name",
        "Example User",
    ]

    assert main(["render", "mobileconfig", *arguments]) == 0
    cli_body = capsysbinary.readouterr().out
    response = TestClient(create_app(config_path=CONFIG)).post(
        "/mobileconfig",
        data={
            "emailaddress": "probe@example.test",
            "cn": "Example User",
        },
    )

    assert response.status_code == 200
    assert response.content == cli_body


def test_render_errors_are_diagnostics_only(
    capsysbinary: pytest.CaptureFixture[bytes],
) -> None:
    assert (
        main(
            [
                "render",
                "autoconfig",
                "--config",
                str(CONFIG),
                "--email",
                "not-an-address",
            ]
        )
        == 2
    )
    captured = capsysbinary.readouterr()
    assert captured.out == b""
    assert captured.err.startswith(b"automx: invalid email address")

    assert (
        main(
            [
                "render",
                "autodiscover",
                "--config",
                str(ROOT / "contrib/production-example/automx.conf"),
                "--email",
                "probe@example.test",
                "--schema",
                "mobilesync",
            ]
        )
        == 2
    )
    captured = capsysbinary.readouterr()
    assert captured.out == b""
    assert b"ActiveSync" in captured.err


def test_render_help_has_no_credentials_or_network_mutation_options(
    capsys: pytest.CaptureFixture[str],
) -> None:
    with pytest.raises(SystemExit) as exited:
        build_parser().parse_args(["render", "autodiscover", "--help"])
    assert exited.value.code == 0
    help_text = capsys.readouterr().out
    assert "--email" in help_text
    assert "--schema {outlook,mobilesync}" in help_text
    for forbidden in ("--password", "--token", "--apply", "--url", "--nameserver"):
        assert forbidden not in help_text

    with pytest.raises(SystemExit) as exited:
        build_parser().parse_args(["render", "mobileconfig", "--help"])
    assert exited.value.code == 0
    help_text = capsys.readouterr().out
    assert "--email" in help_text
    assert "--common-name" in help_text
    assert "--signature-status" in help_text
    for forbidden in ("--password", "--token", "--apply", "--url", "--nameserver"):
        assert forbidden not in help_text
