"""Generate read-only DNS deployment records for automx protocols."""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass

from automx.commands.common import DEFAULT_CONFIG
from automx.commands.pacc import pacc_bytes
from automx.renderers.pacc import pacc_digest_record


@dataclass(frozen=True, slots=True)
class DNSRecord:
    name: str
    type: str
    value: str

    def zone_line(self, ttl: int) -> str:
        value = f'"{self.value}"' if self.type == "TXT" else self.value
        return f"{self.name}. {ttl} IN {self.type} {value}"


def _hostname(value: str, *, option: str) -> str:
    candidate = value.rstrip(".").lower()
    if not candidate or len(candidate) > 253 or any(char.isspace() for char in candidate):
        raise ValueError(f"{option} must be a DNS hostname")
    try:
        labels = tuple(label.encode("idna").decode("ascii") for label in candidate.split("."))
    except UnicodeError as exc:
        raise ValueError(f"{option} must be a DNS hostname") from exc
    if any(not label or len(label) > 63 for label in labels):
        raise ValueError(f"{option} must be a DNS hostname")
    return ".".join(labels)


def deployment_records(
    *, config_path: str, domain: str | None, service_host: str
) -> tuple[str, tuple[DNSRecord, ...]]:
    selected, body = pacc_bytes(config_path, domain)
    selected = _hostname(selected, option="--domain")
    target = _hostname(service_host, option="--service-host")
    records = tuple(
        record
        for record in (
            DNSRecord(f"autoconfig.{selected}", "CNAME", f"{target}."),
            DNSRecord(f"autodiscover.{selected}", "CNAME", f"{target}."),
            DNSRecord(f"_autodiscover._tcp.{selected}", "SRV", f"0 0 443 {target}."),
            DNSRecord(f"ua-auto-config.{selected}", "CNAME", f"{target}."),
            DNSRecord(
                f"_ua-auto-config.{selected}",
                "TXT",
                pacc_digest_record(body),
            ),
        )
        if record.type != "CNAME" or record.name != target
    )
    return selected, records


def register(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    parser = subparsers.add_parser("dns", help="generate DNS deployment material")
    commands = parser.add_subparsers(dest="dns_command", required=True)
    records = commands.add_parser("records", help="print required automx DNS records")
    records.add_argument("--config", default=DEFAULT_CONFIG, help="path to automx.conf")
    records.add_argument("--domain", help="domain to resolve")
    records.add_argument("--service-host", required=True, help="canonical automx HTTPS host")
    records.add_argument("--format", choices=("zone", "json"), default="zone")
    records.add_argument("--ttl", type=int, default=3600, help="zone output TTL")
    records.set_defaults(handler=run_records)


def run_records(args: argparse.Namespace) -> int:
    if not 60 <= args.ttl <= 604_800:
        raise ValueError("--ttl must be between 60 and 604800 seconds")
    domain, records = deployment_records(
        config_path=args.config,
        domain=args.domain,
        service_host=args.service_host,
    )
    if args.format == "json":
        print(
            json.dumps(
                {
                    "domain": domain,
                    "mode": "read-only",
                    "records": [asdict(record) for record in records],
                },
                indent=2,
                sort_keys=True,
            )
        )
    else:
        print("; Generated by automx (read-only; review before applying)")
        for record in records:
            print(record.zone_line(args.ttl))
    return 0
